name: Run Pytest on GitHub Actions

on: [push, pull_request]  # Run tests on every push & PR

jobs:
  test:
    runs-on: ubuntu-latest  # Use Ubuntu as the test environment

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Pull latest code from GitHub

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Choose Python version

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate  # On Windows, use `venv\Scripts\activate`
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          source venv/bin/activate  # Activate virtual environment
          pytest tests/ --maxfail=5 --disable-warnings  # Run tests with warnings disabled
